mahasiswa1KS3 = [{ "nama": "ADIB SULTHON MUAMMAL" },
{ "nama": "AFI DWI AMINURRAHMAH" },
{ "nama": "ANASTASYA KUNSITA DEWI" },
{ "nama": "ANDREW MARULI TUA TAMPUBOLON" },
{ "nama": "AZKAS SALAM" },
{ "nama": "AZMI ZULFANI PUTRI" },
{ "nama": "BAGAS SETYAWAN" },
{ "nama": "BAGINDA SINAGA" },
{ "nama": "CECILIA PUTRI DIANTI SAMOSIR" },
{ "nama": "DILLA LEONYKA PUTRI DEWAYANI" },
{ "nama": "DINA YANTI NAINGGOLAN" },
{ "nama": "DINDA ALFIRA ILMAYANTI" },
{ "nama": "DIVA PUTRA PRATAMA" },
{ "nama": "FARHAN MAULANA" },
{ "nama": "FEZA RAFFA ARNANDA" },
{ "nama": "FITRIA NUR RAHMAWATI" },
{ "nama": "GILANG ABDUL JABBAR" },
{ "nama": "HAMDANI" },
{ "nama": "INAFIANTI KLARISTANIA RILANO" },
{ "nama": "INGGID UTAMI" },
{ "nama": "LILIS DWIYANTI" },
{ "nama": "M. YANDRE FEBRIAN" },
{ "nama": "MUHAMAD IQBAL PUTRA PRATAMA" },
{ "nama": "MUHAMMAD AFNAN ALFIAN" },
{ "nama": "MUHAMMAD DIVA AMRULLAH" },
{ "nama": "MUHAMMAD NUR ALFIAN SYARIF" },
{ "nama": "MUHAMMAD SULTAN HAFIZ" },
{ "nama": "NATALIE MERRY ANGELINA" },
{ "nama": "NUR AFIFAH" },
{ "nama": "NUR AMALIYATUR ROHMAH" },
{ "nama": "RIDHO PANGESTU" },
{ "nama": "SEIZRA AULIA SALSABILA" },
{ "nama": "SHABRINA ALFIRA NISA" },
{ "nama": "SHELA ALFIYANI AMALIA" },
{ "nama": "SONYA ANANTA PANJAITAN" },
{ "nama": "SUHENDRA WIDI PRAYOGA" },
{ "nama": "VENNY SEPTIA HARTONO" },
{ "nama": "YAHYA ABDURROHMAN" }];